== Übungsaufgabe zu Modul 2a (Testing: App)

In dieser Übungsaufgabe werden Unit-Tests für die bestehende Javascript-Funktionalität erstellt. Verwendet werden hierfür die Javascript-Frameworks Mocha (https://mochajs.org/) und Chai (https://www.chaijs.com/).

Sie werden Funktionen der Frameworks nutzen, die auf keiner der Folien dargestellt waren. Werfen Sie aus diesem Grund auch einen Blick auf die Dokumentation der beiden Frameworks.

Es wird außerdem nötig sein, Teile der bestehenden Skripte so umzubauen, dass Sie besser testbar werden.

=== Platzhalter

Nachfolgend sind die spezifischen Parameter, die in der grundlegenden Einführung zu den Übungen erwähnt sind.

|===
|Platzhalter |Wert

|`<initial-github>`
|https://github.com/baitando/dhbw-web/tree/main/02a_testing-mocha-chai/app/initial

|`<initial-download>`
|https://baitando.github.io/down-git/#/home?url=https://github.com/baitando/dhbw-web/tree/main/02a_testing-mocha-chai/app/initial

|`<initial-ide`
|https://stackblitz.com/fork/github/baitando/dhbw-web/tree/main/02a_testing-mocha-chai/app/initial?file=test/tests.html&terminal=stackblitz&title=%C3%9Cbungsaufgabe%20zu%20Modul%201e%20%28Javascript%3A%20App%29&initialpath=test/tests.html
|===

=== Aufgabenbeschreibung

. Machen Sie sich mit dem bestehenden Test-Setup vertraut.
    .. Werfen Sie einen Blick auf die Dateien `test/test.html` und `test/anlage_tests.js`.
    .. Öffnen Sie die Datei `test/test.html` im Browser und sehen Sie sich das Ergebnis an.
    .. Nehmen Sie temporär eine Änderung im erwarteten Ergebnis des Testfalls in `test/anlage_tests.js` vor und prüfen Sie, wie sich die Ausgabe im Browser dadurch verändert.
. Implementieren Sie in `test/anlage_tests.js` einen neuen Testfall für die Methode replaceTask. Es soll geprüft werden, ob ein Task in der Task-Liste erfolgreich ersetzt werden kann.
. Implementieren Sie eine neue Test-Gruppe in der Datei `test/common_tests.js`, die dem Test der Funktionalitäten aus der Datei `js/common.js` dienen soll.
    .. Legen Sie die neue Datei an und implementieren Sie den Grundaufbau.
    .. Erstellen Sie die Grundstruktur für einen neuen Testfall, der sicherstellen soll, dass die Methode loadStoredTasks die gespeicherten Daten aus dem Local Storage liefert.
    .. Ändern Sie die Funktion `loadStoredTasks` so ab, dass beim Funktionsaufruf ein optionaler Parameter mit dem Schlüssel des Eintrages im Local Storage übergeben werden kann. Hinweis: Die Signatur mit optionalem Parameter entspricht `function loadStoredTasks(storageKey = "tasks")`
    .. Implementieren Sie den Testfall, für den Sie bereits die Grundstruktur erstellt haben. Speichern Sie vor dem Aufruf der Methode `loadStoredTasks` einen JSON-String mit den gewünschten Eingabe-Daten im Local Storage und verwenden Sie dafür einen Schlüssel, der sich vom regulären Schlüssel „tasks“ unterscheidet.

Optional können Sie die folgenden Schritte zusätzlich umsetzen:

. Erstellen Sie weitere Testfälle für die bestehenden Javascript-Funktionalitäten der TODO-Anwendung.
. Verwenden Sie die Selenium IDE, um automatisierte Systemtests mit Selenium aufzuzeichnen. Führen Sie die aufgezeichneten Testfälle auch aus und provozieren Sie einen Fehler, indem Sie temporäre Änderungen in der TODO-Anwendung vornehmen.

=== Lösungsbeispiel

Eine beispielhafte Lösung finden Sie auf GitHub unter https://github.com/baitando/dhbw-web/tree/main/02a_testing-mocha-chai/app/result.

Sie können dieses Lösungsbeispiel durch Öffnen der URL https://stackblitz.com/fork/github/baitando/dhbw-web/tree/main/02a_testing-mocha-chai/app/result?file=test/tests.html&terminal=stackblitz&title=L%C3%B6sungsbeispiel%20zu%20%C3%9Cbungsaufgabe%20zu%20Modul%202a%20%28Testing%3A%20App%29&initialpath=test/tests.html im Browser direkt in der Online-Entwicklungsumgebung betrachten.

